# Importando a biblioteca pandas (e outros)

## 1. Criando um ambiente virtual
- cd caminho/para/seu/projeto
- python -m venv .venv
- .venv\Scripts\activate.bat
- pip install pandas

In [12]:
import sys
print(sys.prefix)

in_venv = sys.prefix != sys.base_prefix
print(in_venv)

/home/bernardo/Documentos/cursos_dados/1_introducao_pandas/pandas
True

## 2. Sistema de importação no python
- Built-in modules
- Módulos externos (**pandas**)
    - https://pypi.org/ - gerenciador de pacotes oficiais que o pip usa
    - https://pypi.org/project/pandas/
    - https://github.com/pandas-dev/pandas
- módulos proprios
    - diretorio local (__init__.py)
    - sys.path.insert(0, "/path/to/your/module_directory")
    - export PYTHONPATH="$PYTHONPATH:/path/to/your/module_directory"

In [1]:
import pandas as pd

In [2]:
print(pd.__version__)

3.0.6

## 3. Leitura dos dados

### problemas na estrutura estática:
- sistemas operacionais possuem diferentes filesystems
- o cwd (current work directory) muda entre ide's

In [19]:
PATH = '../data/samp-2025-convencional.parquet'

df = pd.read_parquet(PATH)

df.head()

,DatGeracaoConjuntoDados,NumCNPJAgenteDistribuidora,SigAgenteDistribuidora,NomAgenteDistribuidora,NomTipoMercado,DscModalidadeTarifaria,DscSubGrupoTarifario,DscClasseConsumoMercado,DscSubClasseConsumidor,DscDetalheConsumidor,IdeNucleoCeg,NumCNPJAgenteAcessante,NomAgenteAcessante,DscPostoTarifario,DscOpcaoEnergia,DatCompetencia,Receita Energia (R$),Energia TUSD (kWh),Energia TE (kWh),Número de consumidores
index,,,,,,,,,,,,,,,,,,,,
8,2026-09-15,02341467000120,Âmbar Amazonas,AMBAR ENERGIA AMAZONAS S.A.,Regular,Convencional,B3,Consumo próprio,Não se aplica,Não se aplica,0,37121669900,Não se aplica,Não se aplica,CATIVO,2025-01-01,511300.53,596464.0,596464.0,65.0
28,2026-09-15,02341467000120,Âmbar Amazonas,AMBAR ENERGIA AMAZONAS S.A.,Regular,Convencional,B1,Residencial,Residencial baixa renda  faixa 02,Não se aplica,0,37121669900,Não se aplica,Não se aplica,CATIVO,2025-01-01,3320543.29,7001367.0,7001367.0,27063.0
40,2026-09-15,02341467000120,Âmbar Amazonas,AMBAR ENERGIA AMAZONAS S.A.,Regular,Convencional,B3,Poder público,Não se aplica,Não se aplica,0,37121669900,Não se aplica,Não se aplica,CATIVO,2025-01-01,4444324.48,5184591.0,5184591.0,2698.0
45,2026-09-15,02341467000120,Âmbar Amazonas,AMBAR ENERGIA AMAZONAS S.A.,Regular,Convencional,B3,Comercial,Não se aplica,Não se aplica,0,37121669900,Não se aplica,Não se aplica,CATIVO,2025-01-01,36194514.41,42223403.0,42223403.0,56831.0
95,2026-09-15,02341467000120,Âmbar Amazonas,AMBAR ENERGIA AMAZONAS S.A.,Regular,Convencional,B3,Industrial,Não se aplica,Não se aplica,0,37121669900,Não se aplica,Não se aplica,CATIVO,2025-01-01,1327169.20,1548229.0,1548229.0,809.0

## Caminhos de arquivos

In [49]:
from pathlib import Path
import os 

print(__name__)

"""
df = pd.read_parquet(
    Path(r'../data/samp-2025-convencional.parquet')
)
"""
print(os.getcwd())

pasta_atual = Path(os.getcwd())

print(pasta_atual.parent)

pasta_dados = pasta_atual.with_name('data')
print(pasta_dados)

NOME_ARQUIVO = r'samp-2025-convencional.parquet'
PATH_DATASET = pasta_dados / NOME_ARQUIVO
print(PATH_DATASET)

__main__
/home/bernardo/Documentos/cursos_dados/1_introducao_pandas/src
/home/bernardo/Documentos/cursos_dados/1_introducao_pandas
/home/bernardo/Documentos/cursos_dados/1_introducao_pandas/data
/home/bernardo/Documentos/cursos_dados/1_introducao_pandas/data/samp-2025-convencional.parquet

In [48]:
print(PATH_DATASET.exists())

True

In [50]:
if PATH_DATASET.exists():
    df = pd.read_parquet(PATH_DATASET)

# 2. **Análise Exploratória**

## Entendendo a base de dados

In [52]:
df.head() # 5 primeiras linhas

,DatGeracaoConjuntoDados,NumCNPJAgenteDistribuidora,SigAgenteDistribuidora,NomAgenteDistribuidora,NomTipoMercado,DscModalidadeTarifaria,DscSubGrupoTarifario,DscClasseConsumoMercado,DscSubClasseConsumidor,DscDetalheConsumidor,IdeNucleoCeg,NumCNPJAgenteAcessante,NomAgenteAcessante,DscPostoTarifario,DscOpcaoEnergia,DatCompetencia,Receita Energia (R$),Energia TUSD (kWh),Energia TE (kWh),Número de consumidores
index,,,,,,,,,,,,,,,,,,,,
8,2026-09-15,02341467000120,Âmbar Amazonas,AMBAR ENERGIA AMAZONAS S.A.,Regular,Convencional,B3,Consumo próprio,Não se aplica,Não se aplica,0,37121669900,Não se aplica,Não se aplica,CATIVO,2025-01-01,511300.53,596464.0,596464.0,65.0
28,2026-09-15,02341467000120,Âmbar Amazonas,AMBAR ENERGIA AMAZONAS S.A.,Regular,Convencional,B1,Residencial,Residencial baixa renda  faixa 02,Não se aplica,0,37121669900,Não se aplica,Não se aplica,CATIVO,2025-01-01,3320543.29,7001367.0,7001367.0,27063.0
40,2026-09-15,02341467000120,Âmbar Amazonas,AMBAR ENERGIA AMAZONAS S.A.,Regular,Convencional,B3,Poder público,Não se aplica,Não se aplica,0,37121669900,Não se aplica,Não se aplica,CATIVO,2025-01-01,4444324.48,5184591.0,5184591.0,2698.0
45,2026-09-15,02341467000120,Âmbar Amazonas,AMBAR ENERGIA AMAZONAS S.A.,Regular,Convencional,B3,Comercial,Não se aplica,Não se aplica,0,37121669900,Não se aplica,Não se aplica,CATIVO,2025-01-01,36194514.41,42223403.0,42223403.0,56831.0
95,2026-09-15,02341467000120,Âmbar Amazonas,AMBAR ENERGIA AMAZONAS S.A.,Regular,Convencional,B3,Industrial,Não se aplica,Não se aplica,0,37121669900,Não se aplica,Não se aplica,CATIVO,2025-01-01,1327169.20,1548229.0,1548229.0,809.0

In [70]:
#print(df.columns)
columns = list(df.columns)

for index, column in enumerate(columns):
    print(
        f'[{index+1}] {column}'
    )

[1] DatGeracaoConjuntoDados
[2] NumCNPJAgenteDistribuidora
[3] SigAgenteDistribuidora
[4] NomAgenteDistribuidora
[5] NomTipoMercado
[6] DscModalidadeTarifaria
[7] DscSubGrupoTarifario
[8] DscClasseConsumoMercado
[9] DscSubClasseConsumidor
[10] DscDetalheConsumidor
[11] IdeNucleoCeg
[12] NumCNPJAgenteAcessante
[13] NomAgenteAcessante
[14] DscPostoTarifario
[15] DscOpcaoEnergia
[16] DatCompetencia
[17] Receita Energia (R$)
[18] Energia TUSD (kWh)
[19] Energia TE (kWh)
[20] Número de consumidores

In [72]:
df['SigAgenteDistribuidora'].unique()

array(['Âmbar Amazonas', 'ENEL RJ', 'CEJAMA', 'CELESC', 'CEMIG-D',
       'ELETROCAR', 'Ceraçá', 'CERFOX', 'CERSUL', 'COCEL', 'CEA',
       'COELBA', 'ERO', 'ESE', 'Neoenergia PE', 'ENEL CE', 'COSERN',
       'CEEE-D', 'CHESP', 'CPFL JAGUARI', 'CPFL-PAULISTA', 'ESS', 'ETO',
       'EQUATORIAL AL', 'EQUATORIAL GO', 'EQUATORIAL MA', 'EQUATORIAL PA',
       'CPFL-PIRATINING', 'SULGIPE', 'CERIPa', 'COOPERALIANÇA',
       'CERAL ANITÁPOLIS', 'CERAL-DIS', 'CASTRO-DIS', 'CERSAD DISTRIBUI',
       'CODESAM', 'CERTHIL', 'CERTEL ENERGIA', 'CERMISSÕES', 'CERGRAL',
       'CERPALO', 'CEGERO', 'CERGAPA', 'CEPRAG', 'CERGAL', 'CELETRO',
       'CERIS', 'CEDRAP', 'CERBRANORTE', 'CETRIL', 'CERMC', 'CEMIRIM',
       'CERRP', 'CERCOS', 'CERNHE', 'CEDRI', 'COOPERMILA', 'CERCI',
       'CERPRO', 'CERAL ARARUAMA', 'CERES', 'CERIM', 'CERTREL', 'CERVAM',
       'CEREJ', 'COOPERCOCAL', 'CERMOFUL', 'COOPERA', 'COOPERNORTE',
       'COOPERSUL', 'CERILUZ', 'CERTAJA', 'COORSEL', 'COOPERLUZ',
       'COOPERZEM', 'COPEL-DIS', 'COPREL', 'CRELUZ-D', 'Não Informado',
       'DCELT', 'DEMEI', 'DMED', 'EDP ES', 'EDP SP', 'ELEKTRO',
       'ELETROPAULO', 'EFLUL', 'EFLJC', 'ELFSM', 'EAC', 'EMT', 'EMS',
       'EQUATORIAL PI', 'PACTO ENERGIA PR', 'HIDROPAN', 'LIGHT SESA',
       'MUXENERGIA', 'Neoenergia Brasília', 'UHENPAL', 'RGE SUL', 'EMR',
       'EPB'], dtype=object)

In [98]:

print(
    f"""
    Coluna DatGeracaoConjuntoDados = AAAA-MM-DD upload dados
    # Qtde. DatGeracaoConjuntoDados {df['DatGeracaoConjuntoDados'].nunique()}
    # Valor = {df['DatGeracaoConjuntoDados'].unique()}

    Coluna DatCompetencia = AAAA-MM-DD referência da linha
    # Qtde. DatCompetencia {df['DatCompetencia'].nunique()}
    """
)

    Coluna DatGeracaoConjuntoDados = AAAA-MM-DD upload dados
    # Qtde. DatGeracaoConjuntoDados 1
    # Valor = ['2026-09-15']

    Coluna DatCompetencia = AAAA-MM-DD referência da linha
    # Qtde. DatCompetencia 12

### 1. meta-dados = dados sobre os dados
```
[1] DatGeracaoConjuntoDados
```

### 2. identifica distribuidora
```
[2] NumCNPJAgenteDistribuidora
[3] SigAgenteDistribuidora
[4] NomAgenteDistribuidora
```
### 3. Identifica valor

```
[5] NomTipoMercado
[6] DscModalidadeTarifaria
[7] DscSubGrupoTarifario
[8] DscClasseConsumoMercado
[9] DscSubClasseConsumidor
[10] DscDetalheConsumidor
[11] IdeNucleoCeg
```

### 4. agente acessante
- Distribuidora, Geradora, consumidor do mercado livre etc...
```
[12] NumCNPJAgenteAcessante
[13] NomAgenteAcessante
```
### Dados sobre os valores de energia
```
[14] DscPostoTarifario
[15] DscOpcaoEnergia
```
### Granularidade temporal

```
[16] DatCompetencia
```


### Variáveis numéricas
```
[17] Receita Energia (R$) (float)
[18] Energia TUSD (kWh) (float)
[19] Energia TE (kWh) (float)
[20] Número de consumidores (int)
```